#!/bin/bash

########################################################################
if [[ -z "$script_dir" ]]
then
  echo 'do not run this script directly !'
  echo 'this script is part of run.sh'
  exit -1
fi
########################################################################


########################################################################
# Add your custom entries to this file.
#
# You can override existing variables here: 
# Example:
#   CUSTOM_COUNTRY=DE
#   CUSTOM_KEYMAP=de-latin1-nodeadkeys
#   CUSTOM_KMAP=qwertz/de-latin1
#   CUSTOM_LANGUAGE=de
#   CUSTOM_LAYOUTCODE=de
#   CUSTOM_LOCALE=de_DE.UTF-8
#   CUSTOM_TIMEZONE=Europe/Berlin
#   CUSTOM_VARIANT=German
#
# Or add additional variables you want to use in your other custom files e.g.: c2-custom-menu
# Example:
#   MY_CUSTOM_VARIABLE=my custom value
CUSTOM_COUNTRY=US
CUSTOM_KEYMAP=us
CUSTOM_KMAP=qwerty
CUSTOM_LANGUAGE=en
CUSTOM_LAYOUTCODE=us
CUSTOM_LOCALE=localectl status
CUSTOM_TIMEZONE=America/Los_Angeles
CUSTOM_VARIANT=English
